### ISSUE TITLE
to-do list

### ISSUE THREAD

**Issue by rnair98** [rnair98/lyceum-react-native#3]
- [ ]  review old pull requests
- [ ]  create new screens and components
- [ ]  integrate database & authentication

# How can I help?
* triage issues
   
   * pick a bug, recreate it locally, then fix it
 * match design on Figma
   
   * on existing pages if you notice an inconsistency between Figma and the website you can make a pr to fix it
   * we will be releasing new components that you can build
 
 # Features for contributors to work on
 * [ ]  Swipe & Match
 * [ ] User Profile Creation & Management
 * [ ]  Friends
 
 # Miscellaneous
 * [ ]  course search engine
 * [ ]  recommendation system
 * [ ]  geolocation-based trending course lists
 
 # What about X feature I want to PR to Lyceum?
 Ask me before starting and tell me the problem you are trying to solve with this feature.
